--- 

# install consul for Debian-based distros
- name: install consul by apt
  ansible.builtin.apt:
    pkg: "{{ consul_apt_packages }}"
    state: present
    update_cache: yes
  tags: consul,consul_init
