---
# install consul for Debian-based distros
- name: Install consul by apt
  ansible.builtin.apt:
    pkg: "{{ consul_apt_packages }}"
    state: present
    update_cache: true
  tags: consul,consul_init
