---

# tasks file for consul
- name: set parameters
  set_fact:
    consul_params: "{{ [consul_params_default,consul_params_group_all | default([]),consul_params_group | default([])] | community.general.lists_mergeby('name',recursive=True,list_merge='append_rp') }}"
  tags: consul,consul_config

- name: install packages
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: consul,consul_init

- name: clean config and data directories
  block:
    - name: check if consul is stopped
      ansible.builtin.service:
        name: "{{ consul_service_name }}"
        state: stopped
    - name: clean config dir
      ansible.builtin.file:
        path: "{{ item}"
        state: absent
      with_fileglob:
        - "{{ consul_config_dir }}/*"
        - "{{ consul_data_dir }}/*"
    - name: generate consul token for encryption
      ansible.builtin.command: consul keygen
      register: consul_enc_key
      run_once: true
    - name: put consul token into permanent store
      ansible.builtin.copy:
        content: "{{ consul_enc_key.stdout }}"
        dest: "{{ common_local_store }}/consul-{{ common_domain_name }}.key"
      when: consul_enc_key is defined and consul_enc_key.stdout != ""
      delegate_to: 127.0.0.1
  tags: consul,consul_init
  when: consul_init_force is defined and consul_init_force | bool

- name: set consul_enc_key variable
  set_fact:
    consul_enc_key: "{{ lookup('file', common_local_store + '/consul-' + common_domain_name + '.key') }}"
  tags: consul,consul_config

- name: create configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ consul_config_dir }}/{{ item | basename | regex_replace('.j2') }}"
  with_fileglob:
    - "{{ consul_templates_dir }}/*.j2"
  notify: restart consul
  tags: consul,consul_config

